# Generated by Django 3.0.8 on 2021-08-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210809_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='order',
            name='verified',
        ),
    ]
